[package]
name = "ginger-gitter"
description = "A service to sync PRs and Pipelines to Ginger"
version = "0.1.0"
edition = "2024"
default-run = "ginger-gitter"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
redis = { version = "0.25", features = ["tokio-comp", "connection-manager"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
tokio-cron-scheduler = "0.10"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
utoipa = {version = "2", features = ["json"]}
utoipa-swagger-ui = "2.0"
base64 = "0.22"
serde_yaml = "0.9"
ginger-shared-rs = {version = "0.38.0-nightly.0", organization = "ginger-society"}
jsonwebtoken = "9.3.0"
tempfile = "3"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[[bin]]
name = "ginger-gitter"
path = "src/main.rs"

[[bin]]
name = "ginger-gitter-pipeline-hook"
path = "src/bin/ginger-gitter-pipeline-hook.rs"


[package.metadata]
organization = "ginger-society"