FROM docker.io/gingersociety/rust-rocket-api-builder:latest as builder

ARG GINGER_TOKEN

# Create a new directory for the app
WORKDIR /app
COPY . .
# Run the ginger-auth command and capture the output
# RUN ginger-auth token-login $GINGER_TOKEN
# RUN ginger-connector connect stage
# Build the application in release mode
RUN cargo build --release

# Copy binary from mounted volume into the container filesystem
RUN cp /app/target/release/ginger-gitter /app/ginger-gitter

# Second stage: Create the minimal runtime image
FROM docker.io/gingersociety/rust-rocket-api-runner:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    git-filter-repo \
    openssh-client \
  && rm -rf /var/lib/apt/lists/*


# Copy the compiled binary from the builder stage
COPY --from=builder /app/ginger-gitter /app/

# Set the working directory
WORKDIR /app

# Run the executable when the container starts
ENTRYPOINT ["./ginger-gitter"]