services:
  gitolite:
    build: .
    ports:
      - "8022:22"
      - "2223:2223" # debug port , use it when you want to run sshd manually while the sshd is running on 22 normally but unable to find the issue
    volumes:
      - gitolite-data:/var/lib/git
    secrets:
      - admin_key.pub # available as /run/secrets/admin_key.pub in the container, used to initialize gitolite with the admin's public key

secrets:
  admin_key.pub:
    file: ./admin_key.pub

volumes:
  gitolite-data: